### ISSUE TITLE
Absolute paths in state files make it difficult for multiple people to use this.

### ISSUE THREAD

**Issue by EvanKrall** [Yelp/terraform-provider-gitfile#2]
Several types of paths end up as absolute paths when written to the state file. If someone else uses the same terraform repo, these paths are likely different, so plan is unclean. Ideally, we'd write relative paths only.

**Comment by bobtfish** [comment]
I believe that if you use relative paths, then you're good for multiple users.

It'd be nice to add a check for a leading / in the path and warn/break in this case.

**Comment by bobtfish** [comment]
This is now fixed, can close?

**Comment by EvanKrall** [comment]
Sure, thx
